import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Admin panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-zinc-100 tracking-tight">
        <div className="bg-zinc-400 h-12 flex items-center p-3 w-full justify-between">
          <div className="text-xl">Panel admina</div>
          <div className="flex gap-2 items-center">
            <Link href={`/`} className="font-semibold hover:underline">
              Strona główna
            </Link>
            <Link href={`/users`} className="font-semibold hover:underline">
              Użytkownicy
            </Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
